repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['-i', '--remove-all-unused-imports']
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: ['-l', '120']
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ['--force-single-line-imports', '--profile', 'black']

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [
            '--max-line-length', '120',
            '--max-doc-length', '120',
            '--ignore', 'F821,E402,W503'
        ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        name: Table of Contents
